"""Code generated by the model and dataset scaffolds must import under the moderntsf namespace."""

from __future__ import annotations

import ast
import inspect

from moderntsf.benchmark.commands import new_dataset, new_model

LEGACY = ("benchmark", "data", "models", "tsf_core")


def _imported_modules(source: str) -> list[str]:
    modules = []
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ImportFrom) and node.module:
            modules.append(node.module)
        elif isinstance(node, ast.Import):
            modules.extend(alias.name for alias in node.names)
    return modules


def _string_literals(module) -> list[str]:
    tree = ast.parse(inspect.getsource(module))
    return [n.value for n in ast.walk(tree) if isinstance(n, ast.Constant) and isinstance(n.value, str)]


def test_scaffold_templates_use_the_moderntsf_namespace() -> None:
    offending = []
    for module in (new_model, new_dataset):
        for literal in _string_literals(module):
            for line in literal.splitlines():
                stripped = line.strip()
                if stripped.startswith(("from ", "import ")):
                    head = stripped.split()[1].split(".")[0]
                    if head in LEGACY:
                        offending.append((module.__name__, stripped))
    assert offending == []
