"""Render ``.agents/README.md``, the module index, from the module map.

The index is a projection of :data:`tsflab.agent.modules.MODULES` plus each skill's
frontmatter description and each task's summary; it is never edited by hand. The
repository copy is regenerated by ``tsf repo cards`` and checked by the asset audit;
a project copy (chosen modules only) is written by ``tsf init`` and ``tsf agent sync``.
"""

from __future__ import annotations

from pathlib import Path
import re
import tomllib

from tsflab.agent.modules import ALL_MODULES, CHAIN, MODULES

MARKER = "<!-- generated by `tsf repo cards` from tsflab.agent.modules; do not edit -->"
PROJECT_MARKER = "<!-- generated by `tsf agent sync` from tsflab.agent.modules; do not edit -->"


TITLES = {"autoresearch": "AutoResearch"}


def skill_description(skill_file: Path) -> str:
    """Return the frontmatter ``description`` of one SKILL.md (empty when absent)."""
    match = re.match(r"^---\n(?P<header>.*?)\n---\n", skill_file.read_text(encoding="utf-8"), re.DOTALL)
    found = re.search(r"^description:\s*(.+?)\s*$", match.group("header"), re.MULTILINE) if match else None
    text = found.group(1) if found else ""
    return text[1:-1].strip() if len(text) >= 2 and text[0] == text[-1] and text[0] in "\"'" else text


def one_line(description: str) -> str:
    """The first sentence of a description."""
    match = re.match(r"(.+?\.)(?:\s|$)", description)
    return match.group(1) if match else description


def render_index(source: Path, modules: list[str] | None = None, *, project: bool = False) -> str:
    """Render the module index for ``modules`` from the assets under ``source`` (a ``.agents`` dir)."""
    chosen = list(ALL_MODULES if modules is None else modules)
    lines = [
        "# Agent assets by module",
        "",
        PROJECT_MARKER if project else MARKER,
        "",
        "Every skill and task template belongs to exactly one module. The chain is",
        "Data -> Models -> Experiments -> Release; each module produces context that",
        "AutoResearch reads. Maintenance keeps the whole sound and is optional in a project.",
        "Skills live at `skills/<name>/SKILL.md`, tasks at `tasks/<name>.toml`",
        "(`tsf agent task list|show|render`); contracts are in `STANDARDS.md` when present.",
    ]
    for name in chosen:
        info = MODULES[name]
        role = "chain" if name in CHAIN else "beside the chain; opt-in, needs a TSFLab checkout"
        purpose = str(info["purpose"])
        lines += ["", f"## {TITLES.get(name, name.capitalize())}", "", f"{purpose[0].upper()}{purpose[1:]} ({role}).", "", "Skills:"]
        for skill in info["skills"]:  # type: ignore[union-attr]
            description = one_line(skill_description(source / "skills" / skill / "SKILL.md"))
            lines.append(f"- [`{skill}`](skills/{skill}/SKILL.md): {description}")
        tasks = list(info["tasks"])  # type: ignore[arg-type]
        if tasks:
            lines += ["", "Tasks:"]
            for task in tasks:
                summary = tomllib.loads((source / "tasks" / f"{task}.toml").read_text(encoding="utf-8"))["summary"]
                lines.append(f"- [`{task}`](tasks/{task}.toml): {summary}")
        commands = ", ".join(f"`{command}`" for command in info["commands"])  # type: ignore[union-attr]
        lines += ["", f"Entry commands: {commands}.", "", f"Context produced: {info['context']}."]
    return "\n".join(lines) + "\n"
