[model]
name = "Esiformer"

[model.params]
enc_in = 7
interpolation = "two_aver"
sparse_ffn = true
sparsity = 0.3
d_model = 128
n_heads = 8
e_layers = 1
d_ff = 128
dropout = 0.1
activation = "gelu"
use_norm = true
use_marks = true
freq = "h"
