[model]
name = "PCATransformer"

[model.params]
enc_in = 7
n_components = 2
d_model = 512
n_heads = 8
e_layers = 2
d_layers = 1
d_ff = 2048
dropout = 0.1
activation = "gelu"
embed = "timeF"
freq = "h"
